name: prtm
channels:
  - conda-forge
  - bioconda
  - pytorch
  - dglteam/label/cu118
  - pyg
  - nvidia
dependencies:
  - conda-forge::python=3.10
  - conda-forge::setuptools=59.5.0
  - conda-forge::pip
  - conda-forge::openmm==8.0.0
  - conda-forge::pdbfixer==1.9
  - conda-forge::cudatoolkit=11.8.*
  - bioconda::tmalign
  - bioconda::hmmer==3.3.2
  - bioconda::hhsuite==3.3.0
  - bioconda::kalign2==2.04
  - pytorch::pytorch==2.0.1
  - pytorch-cuda=11.8
  - dglteam/label/cu118::dgl
  - pytorch-lightning==2.0.2
  - astropy==5.3
  - wandb==0.15.3
  - biopandas==0.4.1
  - biopython==1.81
  - biotite==0.37.0
  - chex==0.1.7
  - deepspeed==0.12.2
  - dgllife==0.3.2
  - dm-haiku==0.0.8
  - dm-tree==0.1.7
  - e3nn==0.5.1
  - einops==0.6.1
  - hydra-core==1.3.2
  - jax==0.4.11
  - louvain==0.8.0
  - modelcif==0.7
  - conda-forge::networkx==3.1
  - numba==0.57.0
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - seaborn
  - sympy
  - tqdm
  - nglview
  - jupyterlab
  - matplotlib
  - omegaconf==2.3.0
  - conda-forge::openbabel==3.1.1
  - optax==0.1.5
  - conda-forge::rdkit==2023.03.1
  - conda-forge::scanpy==1.9.3
  - pyg::pyg==2.3.0
  - pyg::pytorch-sparse==0.6.17
  - pyg::pytorch-scatter==2.1.1
  - pyg::pytorch-cluster==1.6.1
  - ray-core==2.4.0
  - transformers==4.29.2
  - tensorboard==2.11.2
  - spyrmsd==0.5.2 
  - python-igraph==0.10.3
  - pynvml==11.0.0
  - decorator==5.1.0
  - pip:
      - boto3
      - botocore
      - opt-einsum-fx>=0.1.4
      - opt-einsum>=3.3.0
      - charset-normalizer
      - colossalai
      - gdown
      - gitpython
      - huggingface_hub
      - immutabledict
      - libmsym
      - lie_learn
      - lifelines
      - mpl-scatter-density
      - packaging
      - prettytable
      - protobuf
      - py3Dmol
      - pyaml
      - pyfaidx
      - pytest
      - requests
      - subword-nmt
      - threadpoolctl
      - typing-extensions
      - urllib3
      - wget
      - git+https://github.com/NVIDIA/dllogger.git