args_file: /data/rsg/nlp/sdobers/amine/diffdock-protein/ckpts/dips_confidence_model_20_poses/args.yaml
atom_max_neighbors: 8
atom_radius: 5
batch_size: 48
c_alpha_max_neighbors: 10
checkpoint_path: /data/rsg/nlp/sdobers/amine/diffdock-protein/ckpts/dips_confidence_model_20_poses
config_file: config/dips_esm_confidence.yaml
cross_cutoff_bias: 40
cross_cutoff_weight: 3
cross_dist_embed_dim: 32
cross_max_dist: 80
data_file: /data/rsg/nlp/sdobers/data/DIPS/data_file.csv
data_path: /data/rsg/nlp/sdobers/data/DIPS/pairs_pruned
dataset: dips
debug: false
dist_embed_dim: 32
dropout: 0.0
dynamic_max_cross: true
ebd_type: continuous
embedding_scale: 10000
embedding_type: sinusoidal
encoder_type: e3nn
energy_loss_weight: 1.0
entity: null
epochs: 2000
filtering_model_path: null
generate_n_predictions: 7
gpu: 2
group: null
hidden_size: 64
knn_size: 20
lm_embed_dim: 1280
log_file: /data/rsg/nlp/sdobers/amine/diffdock-protein/ckpts/dips_confidence_model_20_poses/results.yaml
log_frequency: 10
logger: wandb
lr: 0.001
matching_maxiter: 20
matching_popsize: 20
max_lig_size: null
max_poses: 100
max_radius: 30.0
metric: loss
mirror_ligand: false
mode: train
model_type: e3nn
multiplicity: 10
no_batch_norm: true
no_final_noise: false
no_graph_cache: true
no_lm_cache: false
no_random: false
no_torsion: true
no_tqdm: false
ns: 16
num_conv_layers: 4
num_folds: 1
num_gpu: 2
num_inference_complexes: null
num_inference_complexes_train_data: 1200
num_samples: null
num_steps: 40
num_workers: 0
nv: 4
ode: false
patience: 2000
pose_path: data
prediction_storage: false
project: Confidence model
recache: false
receptor_radius: 30
remove_hs: false
resolution: residue
rmsd_classification_cutoff: 5
rmsd_prediction: false
rot_s_max: 1.65
rot_s_min: 0.01
rot_weight: 0.5
run_inference_without_confidence_model: false
run_name: dips_confidence_model_20_poses
sample_train: true
samples_directory: /data/rsg/nlp/sdobers/DIPS/confidence_full_20_poses
save_model_every: 10
save_path: /data/rsg/nlp/sdobers/amine/diffdock-protein/ckpts/dips_confidence_model_20_poses
save_pred: false
scale_by_sigma: true
score_loss_weight: 0.0
score_model_path: null
seed: 0
sigma_embed_dim: 32
temp_psi: 0.0
temp_sampling: 1.0
temp_sigma_data_rot: 0.5
temp_sigma_data_tr: 0.5
tensorboard_path: runs
test_fold: 0
tor_s_max: 3.14
tor_s_min: 0.0314
tor_weight: 0.0
torchhub_path: /data/rsg/nlp/sdobers/ruslan/hub
tr_s_max: 30.0
tr_s_min: 0.01
tr_weight: 0.5
tuned_param: ''
use_complex_rmsd: false
use_orientation_features: false
use_randomized_confidence_data: false
use_second_order_repr: false
use_unbound: false
val_inference_freq: 10
visualization_path: ./visualization
visualize_n_val_graphs: 5
wandb_run_name: null
wandb_sweep: false
weight_decay: 0.0
