name: CI
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    tags: '*'
  schedule:
    - cron: '00 04 * * 1' # 4am every Monday
  workflow_dispatch:
jobs:
  test_repo:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.9]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install PyTorch
      run: pip install torch==1.8.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
    - name: Install other dependencies
      run: pip install numpy
    - name: Test install
      run: pip install .
    - name: Test help
      run: time python bin/dmpfold -h
    - name: Test defaults
      run: time python bin/dmpfold -i dmpfold/example/PF10963.aln
    - name: Test Python module
      run: time python -c "from dmpfold import aln_to_coords; print(aln_to_coords('dmpfold/example/PF10963.aln'))"
  test_pypi:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.9]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install PyTorch
      run: pip install torch==1.8.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
    - name: Test install
      run: pip install dmpfold
    - name: Test help
      run: time dmpfold -h
    - name: Test defaults
      run: time dmpfold -i dmpfold/example/PF10963.aln
    - name: Test Python module
      run: time python -c "from dmpfold import aln_to_coords; print(aln_to_coords('dmpfold/example/PF10963.aln'))"
