# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.dev71+g65371a0.d20230607'
__version_tuple__ = version_tuple = (0, 1, 'dev71', 'g65371a0.d20230607')
